version: '3.8'

services:
  ms-ticket-manager:
    image: brunobaldiga/ms-ticket-manager:latest
    container_name: ms-ticket-manager
    restart: always
    ports:
      - "9001:9001"
    environment:
      - SERVER_PORT=9001
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://10.0.8.201:8080/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://10.0.8.201:27017/db_ticket
      - SPRING_RABBITMQ_HOST=10.0.8.201
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
      - SPRING_MAIL_USERNAME=awdadadadwawdaw@gmail.com
      - SPRING_MAIL_PASSWORD=ychu nxgz rnpe utbt
