version: '3.8'

services:
  ms-event-manager:
    image: brunobaldiga/ms-event-manager:latest
    container_name: ms-event-manager
    restart: always
    ports:
      - "9000:9000"
    environment:
      - SERVER_PORT=9000
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://10.0.8.201:8080/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://10.0.8.201:27017/db_event
      - SPRING_RABBITMQ_HOST=10.0.8.201
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
