version: '3.8'

services:
  eureka-server:
    image: brunobaldiga/eureka-server:latest
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
