version: '3.8'

services:
  eureka-server:
    image: brunobaldiga/eureka-server:latest
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761

  ms-event-manager:
    image: brunobaldiga/ms-event-manager:latest
    container_name: ms-event-manager
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - eureka-server
      - mongodb
      - rabbitmq
    environment:
      - SERVER_PORT=9000
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/db_event
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

  ms-ticket-manager:
    image: brunobaldiga/ms-ticket-manager:latest
    container_name: ms-ticket-manager
    restart: always
    ports:
      - "9001:9001"
    depends_on:
      - eureka-server
      - mongodb
      - rabbitmq
    environment:
      - SERVER_PORT=9001
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/db_ticket
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_MAIL_USERNAME=awdadadadwawdaw@gmail.com
      - SPRING_MAIL_PASSWORD=ychu nxgz rnpe utbt

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    command: mongod --auth

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
