spring:
  application:
    name: ms-event-manager
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

server:
  port: ${SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
