spring:
  application:
    name: ms-ticket-manager
  data:
    mongodb:
      uri: mongodb://localhost:27017/db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: awdadadadwawdaw@gmail.com
    password: ychu nxgz rnpe utbt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mq:
  queues:
    email-queue: email-queue

server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka