spring:
  application:
    name: ms-event-manager
  data:
    mongodb:
      uri: mongodb://localhost:27017/db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka