spring:
  application:
    name: ms-ticket-manager
  data:
    mongodb:
      uri: mongodb://localhost:27017/db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mq:
  queues:
    request-event-details: request-event-details
    response-event-details: response-event-details

server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka